/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earthquakes-2010-2011-3a57cfbbcb1c45278c13bc66886dd6ee
Title: Earthquakes - 2010 & 2011
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { a } from '@react-spring/three'
import WorldScene from '../assets/3d/WiredWorld.glb'


const World = (props) => {
    const WorldRef = useRef()
    const { nodes, materials } = useGLTF(WorldScene)

    // Usamos useFrame para actualizar la rotación en cada frame
    useFrame(() => {
        if (WorldRef.current) {
            // Modifica aquí la velocidad y dirección de la rotación según sea necesario
            WorldRef.current.rotation.y += 0.002; // Por ejemplo, velocidad de rotación
        }
    });
    return (
        <a.group ref={WorldRef} {...props}>
        <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <points geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
            <points geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
            <points geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
            <points geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
        </a.group>
        </a.group>
    )
}

export default World